# Generated by Django 4.0.6 on 2022-07-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Double',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('datanascimento', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
