# Generated by Django 4.0.6 on 2022-07-08 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='double',
            old_name='datanascimento',
            new_name='data_nascimento',
        ),
    ]
